import { cn } from "@repo/libs/utils";
import "@repo/ui/dist/index.css";
import { Providers } from "@repo/ui/src/components/providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavrBar from "../components/nav-bar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <Providers>
      <html lang="en">
        <body
          className={cn(
            "container py-7 h-screen relative bg-black grid grid-cols-5 gap-5",
            inter.className,
          )}
        >
          <div className="col-span-1 card-blur ">
            <NavrBar />
          </div>
          <div className="col-span-4">{children}</div>
        </body>
      </html>
    </Providers>
  );
}
